parameters:
  - name: stageName
    type: string
  - name: stageDisplayName
    type: string
  - name: jobName
    type: string
  - name: jobDisplayName
    type: string
  - name: CYPRESS_BASE_URL
    type: string
  - name: prefix
    type: string
  

stages:
  - stage: ${{ parameters.stageName }}
    displayName: ${{ parameters.stageDisplayName }}
    jobs:
      - job: ${{ parameters.jobName }}
        displayName: ${{ parameters.jobDisplayName }}
        pool:
          name: ${{ parameters.prefix }}-ECE-managed-devops-pool
        steps:
          - task: Bash@3
            inputs:
              targetType: inline
              script: |
                cd tests
                npm install
          - task: Bash@3
            displayName: 'RunTests'
            inputs:
              targetType: inline
              script: |
                cd tests
                export CYPRESS_BASE_URL="${{ parameters.CYPRESS_BASE_URL }}"
                export CYPRESS_DFE_ADMIN_EMAIL_ADDRESS="$(DFE_ADMIN_EMAIL_ADDRESS)"
                export CYPRESS_DFE_ADMIN_PASSWORD="$(DFE_ADMIN_PASSWORD)"
                npm run adminE2e:electron
          - task: Bash@3
            condition: always()
            displayName: 'Generate report'
            inputs:
              targetType: inline
              script: |
                cd tests
                npm run combine:reports
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Cypress Screenshot Files'
            condition: failed()
            inputs:
              pathToPublish: 'tests/cypress/screenshots/'
              artifactName: 'screenshots'
          - task: PublishTestResults@2
            condition: always()
            displayName: 'Publish test results'
            inputs:
              testResultsFiles: '**/combined-report.xml'
              searchFolder: 'tests'