pool:
  name: Azure Pipelines
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
  
## -- Build Application Stage -- ##
  - template: templates/build-app-template.yml.yml
    parameters:
      stageName: 'BuildApp'
      displayName: 'Build App'
## -- Build Application Stage -- ##

  - stage: DeployAppCypress
    displayName: Deploy App Cypress
    jobs:
      - deployment: cypressdeploy
        displayName: Deploy App Cypress
        pool:
          name: Azure Pipelines
          vmImage: 'ubuntu-latest'
        environment: CYPRESS
        strategy:
          runOnce:
            preDeploy:
              steps:
                - task: DownloadPipelineArtifact@2
                  inputs:
                    buildType: 'current'
                    targetPath: '$(Pipeline.Workspace)'
            deploy:
              steps:
                - task: AzureRmWebAppDeployment@4
                  inputs:
                    ConnectionType: 'AzureRM'
                    azureSubscription: 's203d.azdo.deployment'
                    appType: 'webApp'
                    WebAppName: 'ece-dev-as-cypress'
                    packageForLinux: '$(Pipeline.Workspace)/checkChildcareEligibilityAdmin/CheckChildcareEligibility.Admin.zip'
                - task: Bash@3
                  inputs:
                    targetType: inline
                    script: |
                      cd $(Pipeline.Workspace)/checkChildcareEligibilityAdmin/tests
                      npm install
                - task: Bash@3
                  displayName: 'RunTests'
                  inputs:
                    targetType: inline
                    script: |
                      cd $(Pipeline.Workspace)/checkChildcareEligibilityAdmin/tests
                      export CYPRESS_BASE_URL="$(CYPRESS_BASE_URL_CYPRESS)"
                      export CYPRESS_DFE_ADMIN_EMAIL_ADDRESS="$(DFE_ADMIN_EMAIL_ADDRESS)"
                      export CYPRESS_DFE_ADMIN_PASSWORD="$(DFE_ADMIN_PASSWORD)"
                      npm run adminE2e:electron
                - task: Bash@3
                  condition: always()
                  displayName: 'Generate report'
                  inputs:
                    targetType: inline
                    script: |
                      cd $(Pipeline.Workspace)/checkChildcareEligibilityAdmin/tests
                      npm run combine:reports
                - task: PublishBuildArtifacts@1
                  displayName: 'Publish Cypress Screenshot Files'
                  condition: failed()
                  inputs:
                    PathtoPublish: '$(Pipeline.Workspace)/checkChildcareEligibilityAdmin/tests/cypress/screenshots/'
                    ArtifactName: 'screenshots'
                - task: PublishTestResults@2
                  condition: always()
                  displayName: 'Publish test results'
                  inputs:
                    testResultsFiles: '**/combined-report.xml'
                    searchFolder: '$(Pipeline.Workspace)/checkChildcareEligibilityAdmin/tests'
